### ISSUE TITLE
When "eating" a dot, a new dot may appear within the snake

### ISSUE THREAD

**Issue by Structed** [Lupusa87/BlazorGameSnake#1]
Remark: Thank you for all your cool demos!

# Expected Behaviour
## Option 1
When "eating" a (red) dot, a new dot should appear on any other tile but:
* An obstacle
* Withing the snake or it's tail, thus also not on the same spot the previous food-dot was
## Option 2
When "eating" a (red) dot, a new dot should appear on any other tile but:
* An obstacle
* Not on the same tile the previous food dot was

# Actual Behaviour
After eating a dot, a new red dot may appear within the snake's tail. On the next frame redraw, it will disappear.

**Comment by Lupusa87** [comment]
Sorry I did not notified about new issue, I saw it by occasion.
Will check later.
I did this dame about 4-5 months ago and did not touch it after.
My goal was to do some game for demonstration purposes and hope it serves this goal.

Improvement will be good bet I am busy working in another project.

You can make PR, but as I remember because I had limited time I did code was big mess.

I had this game written in typescript and posted it in very limited time.

**Comment by Structed** [comment]
Well, I assumed so, so the Issue was more or less a joke. I don't expect 
this to be fixed because it's obviously just a demo project showing the 
capabilities of Blazor.

If I feel like and have too much time, I'll add a PR :)

Am 2. März 2019 21:44:29 schrieb Vakhtangi Abashidze 
<notifications@github.com>:
